import nextConfig from "eslint-config-next";

const eslintConfig = [
  // Prisma-generated client - regenerated by `npm install`, never hand-edited.
  { ignores: ["src/generated/**"] },
  ...nextConfig,
];

export default eslintConfig;
